BEGIN;

CREATE SCHEMA IF NOT EXISTS knowledge_base;

CREATE TABLE IF NOT EXISTS knowledge_base.knowledge_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_key TEXT NOT NULL UNIQUE,
  filename TEXT NOT NULL,
  source_path TEXT,
  current_version_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS knowledge_base.knowledge_document_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES knowledge_base.knowledge_documents(id) ON DELETE CASCADE,
  version_number INTEGER NOT NULL CHECK (version_number > 0),
  filename TEXT NOT NULL,
  source_path TEXT,
  sha256 TEXT NOT NULL UNIQUE CHECK (sha256 ~ '^[a-f0-9]{64}$'),
  file_size BIGINT NOT NULL CHECK (file_size >= 0),
  status TEXT NOT NULL CHECK (status IN ('PROCESSING','SUCCESS','FAILED')),
  title TEXT,
  country TEXT,
  client TEXT,
  funding_institution TEXT,
  sector TEXT,
  project_type TEXT,
  metadata JSONB,
  chunk_count INTEGER NOT NULL DEFAULT 0 CHECK (chunk_count >= 0),
  embedding_count INTEGER NOT NULL DEFAULT 0 CHECK (embedding_count >= 0),
  embedding_dimension INTEGER CHECK (embedding_dimension > 0),
  qdrant_collection TEXT NOT NULL,
  processing_version TEXT NOT NULL,
  error_code TEXT,
  error_stage TEXT,
  error_message TEXT,
  processed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (document_id, version_number)
);

DO $$ BEGIN
  ALTER TABLE knowledge_base.knowledge_documents
    ADD CONSTRAINT knowledge_documents_current_version_fk
    FOREIGN KEY (current_version_id)
    REFERENCES knowledge_base.knowledge_document_versions(id)
    ON DELETE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS knowledge_base.knowledge_ingestion_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT REFERENCES knowledge_base.knowledge_documents(id) ON DELETE SET NULL,
  document_version_id BIGINT REFERENCES knowledge_base.knowledge_document_versions(id) ON DELETE SET NULL,
  status TEXT NOT NULL CHECK (status IN ('PROCESSING','SUCCESS','FAILED','SKIPPED_DUPLICATE')),
  chunk_count INTEGER NOT NULL DEFAULT 0,
  embedding_count INTEGER NOT NULL DEFAULT 0,
  error_code TEXT,
  error_stage TEXT,
  error_message TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS knowledge_versions_document_idx ON knowledge_base.knowledge_document_versions(document_id, version_number DESC);
CREATE INDEX IF NOT EXISTS knowledge_versions_status_idx ON knowledge_base.knowledge_document_versions(status);
CREATE INDEX IF NOT EXISTS knowledge_versions_country_idx ON knowledge_base.knowledge_document_versions(country);
CREATE INDEX IF NOT EXISTS knowledge_versions_client_idx ON knowledge_base.knowledge_document_versions(client);
CREATE INDEX IF NOT EXISTS knowledge_versions_funding_idx ON knowledge_base.knowledge_document_versions(funding_institution);
CREATE INDEX IF NOT EXISTS knowledge_versions_sector_idx ON knowledge_base.knowledge_document_versions(sector);
CREATE INDEX IF NOT EXISTS knowledge_versions_project_type_idx ON knowledge_base.knowledge_document_versions(project_type);
CREATE INDEX IF NOT EXISTS knowledge_versions_metadata_idx ON knowledge_base.knowledge_document_versions USING GIN(metadata);
CREATE INDEX IF NOT EXISTS knowledge_runs_status_idx ON knowledge_base.knowledge_ingestion_runs(status, started_at DESC);

COMMIT;
