BEGIN;

-- Phase 2 - classification infrastructure. Additive only.
--
-- Does NOT alter knowledge_base.archive_files, archive_scan_runs, or
-- archive_source_roots in any way. The existing ~40,853-row Phase 1
-- inventory (20260828_archive_cartography.sql) is completely unaffected -
-- this migration creates one new, empty, independent table.
--
-- Classification is modeled as a separate 1:1 table rather than by reusing
-- archive_files.processing_status (a single unconstrained TEXT column).
-- Phase 2 needs two independent classification dimensions (technical_bucket,
-- knowledge_category) plus lifecycle state, provenance (method/confidence/
-- reason), and reviewer identity - that does not fit one column without
-- overloading its meaning. archive_files.processing_status is left exactly
-- as-is (still NOT NULL DEFAULT 'not_classified') and is neither read nor
-- written by this migration or by any Phase 2 code; it is intentionally not
-- repurposed here, to avoid a non-additive semantic change to Phase 1 data.
--
-- A file with no row in this table is implicitly UNCLASSIFIED. That is the
-- state of all ~40,853 existing Phase 1 files after this migration runs,
-- achieved by inserting nothing for them - not by mutating archive_files.
--
-- Reviewer/classifier identity references public.app_users(id), the same
-- user table and FK pattern already used for reviewer-style columns
-- elsewhere (see e.g. public.appels_offres.commercial_owner_assigned_by_user_id
-- in 20260806_appels_offres_commercial_ownership_phase5.sql).

CREATE TABLE IF NOT EXISTS knowledge_base.archive_file_classifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- 1:1 with archive_files. UNIQUE (not just indexed) enforces at most one
  -- classification row per file. Cascades on delete, matching how
  -- archive_files itself cascades from archive_source_roots.
  archive_file_id BIGINT NOT NULL UNIQUE
    REFERENCES knowledge_base.archive_files(id) ON DELETE CASCADE,

  -- Technical bucket (Step 3): deterministic, extension-only pre-filter.
  -- Nullable until a technical filter pass has actually run for this file.
  technical_bucket TEXT
    CHECK (technical_bucket IN (
      'BUSINESS_DOCUMENT',
      'TECHNICAL_FILE',
      'IMAGE',
      'ARCHIVE',
      'SOFTWARE_SYSTEM',
      'UNKNOWN'
    )),

  -- Knowledge category: only meaningful for potentially useful documents.
  -- UNKNOWN is a valid, non-failure outcome - never treat it as an error.
  knowledge_category TEXT
    CHECK (knowledge_category IN (
      'CDC',
      'OFFER',
      'PROJECT',
      'METHODOLOGY',
      'CV_CONSULTANT',
      'COMMERCIAL',
      'FINANCIAL',
      'ADMINISTRATIVE',
      'OTHER',
      'UNKNOWN'
    )),

  -- Lifecycle. Every file starts UNCLASSIFIED. AI_PROPOSED must never be
  -- treated as validated - only a human moving state to VALIDATED confirms
  -- anything.
  classification_state TEXT NOT NULL DEFAULT 'UNCLASSIFIED'
    CHECK (classification_state IN (
      'UNCLASSIFIED',
      'AUTO_FILTERED',
      'AI_PROPOSED',
      'NEEDS_REVIEW',
      'VALIDATED'
    )),

  -- Provenance of the current classification_state. CLOUD_AI is
  -- deliberately not a valid value (local-only requirement).
  classification_method TEXT
    CHECK (classification_method IN ('RULE', 'LOCAL_AI', 'HUMAN')),

  -- Only meaningful for RULE/LOCAL_AI proposals; NULL for HUMAN-set or
  -- not-yet-classified rows. NULL passes this CHECK (Postgres treats an
  -- unknown CHECK result as a pass), so the column stays nullable.
  classification_confidence NUMERIC(4, 3)
    CHECK (classification_confidence BETWEEN 0 AND 1),

  classification_reason TEXT,

  classified_at TIMESTAMPTZ,
  classified_by_user_id BIGINT REFERENCES public.app_users(id) ON DELETE SET NULL,

  reviewed_at TIMESTAMPTZ,
  reviewed_by_user_id BIGINT REFERENCES public.app_users(id) ON DELETE SET NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS archive_file_classifications_state_idx
  ON knowledge_base.archive_file_classifications(classification_state);
CREATE INDEX IF NOT EXISTS archive_file_classifications_technical_bucket_idx
  ON knowledge_base.archive_file_classifications(technical_bucket);
CREATE INDEX IF NOT EXISTS archive_file_classifications_knowledge_category_idx
  ON knowledge_base.archive_file_classifications(knowledge_category);

COMMIT;
