BEGIN;

-- Additive only. Does NOT modify knowledge_base.knowledge_documents,
-- knowledge_base.knowledge_document_versions, knowledge_base.knowledge_ingestion_runs,
-- or knowledge_base.historical_project_records in any way. This is a
-- deliberately INDEPENDENT filesystem-level catalog, not an extension of the
-- CDC-ingestion tables: those tables' invariants (sha256 UNIQUE per document
-- identity, a status lifecycle that assumes Docling/embedding/Qdrant all
-- ran) model a document going through the CDC RAG pipeline, not a bare
-- "file seen on disk" fact. Mixing the two would either violate those
-- invariants (many archive files intentionally share a sha256 - that is
-- exactly what duplicate detection means here) or force meaningless NULLs
-- into CDC-specific business columns. See docs/ARCHIVE_CARTOGRAPHY_V1.md.
--
-- Phase 1 (this migration) stores ONLY filesystem facts: identity, size,
-- timestamps, and content hash. No AI-derived or classification field
-- (document type, project/CDC/CV, client, sector, ...) is created here -
-- Phase 2 will add those additively, without touching this migration.

CREATE TABLE IF NOT EXISTS knowledge_base.archive_source_roots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Internal locator only (Step 5): never returned raw by a future
  -- user-facing API. Files reference this row by id + relative_path
  -- instead of embedding an absolute path on every row.
  root_path TEXT NOT NULL UNIQUE,
  label TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS knowledge_base.archive_scan_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_root_id BIGINT NOT NULL REFERENCES knowledge_base.archive_source_roots(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  files_seen INTEGER NOT NULL DEFAULT 0 CHECK (files_seen >= 0),
  files_new INTEGER NOT NULL DEFAULT 0 CHECK (files_new >= 0),
  files_unchanged INTEGER NOT NULL DEFAULT 0 CHECK (files_unchanged >= 0),
  files_changed INTEGER NOT NULL DEFAULT 0 CHECK (files_changed >= 0),
  files_failed INTEGER NOT NULL DEFAULT 0 CHECK (files_failed >= 0),
  total_bytes BIGINT NOT NULL DEFAULT 0 CHECK (total_bytes >= 0),
  duplicate_files INTEGER NOT NULL DEFAULT 0 CHECK (duplicate_files >= 0),
  error_message TEXT
);

CREATE TABLE IF NOT EXISTS knowledge_base.archive_files (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_root_id BIGINT NOT NULL REFERENCES knowledge_base.archive_source_roots(id) ON DELETE CASCADE,

  -- FILE IDENTITY (Step 3): source root + relative path. Deliberately NOT
  -- derived from scan order or array position, and deliberately separate
  -- from CONTENT DUPLICATE IDENTITY (sha256, below) - two files can share
  -- one sha256 (duplicates) while each keeps its own distinct file identity.
  relative_path TEXT NOT NULL,
  filename TEXT NOT NULL,
  extension TEXT,
  parent_folder TEXT,

  size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
  modified_at TIMESTAMPTZ,

  -- CONTENT DUPLICATE IDENTITY (Step 3/7). Deliberately NOT unique - two
  -- files legitimately sharing a hash is exactly what "duplicate" means;
  -- duplicate groups are computed on demand from this column (GROUP BY),
  -- not precomputed/stored, so there is nothing to keep in sync.
  sha256 TEXT CHECK (sha256 ~ '^[a-f0-9]{64}$'),

  -- discovered: seen on disk, not yet hashed.
  -- hashed: sha256 computed successfully.
  -- failed: stat/read/hash raised (Step 6) - never aborts the batch.
  discovery_status TEXT NOT NULL DEFAULT 'discovered'
    CHECK (discovery_status IN ('discovered', 'hashed', 'failed')),
  error_message TEXT,

  -- Reserved for Phase 2 classification (CDC/PROJECT/OFFER/METHODOLOGY/
  -- CV/OTHER/UNKNOWN). Deliberately no CHECK constraint yet - Phase 2 owns
  -- defining and constraining this value set in its own additive migration.
  processing_status TEXT NOT NULL DEFAULT 'not_classified',

  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (source_root_id, relative_path)
);

CREATE INDEX IF NOT EXISTS archive_files_sha256_idx ON knowledge_base.archive_files(sha256);
CREATE INDEX IF NOT EXISTS archive_files_discovery_status_idx ON knowledge_base.archive_files(discovery_status);
CREATE INDEX IF NOT EXISTS archive_files_processing_status_idx ON knowledge_base.archive_files(processing_status);
CREATE INDEX IF NOT EXISTS archive_files_extension_idx ON knowledge_base.archive_files(extension);
CREATE INDEX IF NOT EXISTS archive_files_source_root_idx ON knowledge_base.archive_files(source_root_id);
CREATE INDEX IF NOT EXISTS archive_scan_runs_source_root_idx ON knowledge_base.archive_scan_runs(source_root_id, started_at DESC);
CREATE INDEX IF NOT EXISTS archive_scan_runs_status_idx ON knowledge_base.archive_scan_runs(status);

COMMIT;
