BEGIN;

-- Phase 2 - classification review history. Additive only.
--
-- Does NOT alter knowledge_base.archive_files, archive_scan_runs,
-- archive_source_roots, or archive_file_classifications (from
-- 20260829_archive_cartography_classification.sql) in any way. This
-- migration creates one new, empty, append-only table.
--
-- archive_file_classifications (the sibling table) stores only the CURRENT
-- classification for a file and can be legitimately overwritten by a later
-- human review - that is by design, not a bug. This table exists purely so
-- that overwrite is never silently lossy: every human review additionally
-- appends one immutable event row here recording what the value was before
-- and after the change.
--
-- This is intentionally NOT the tender-specific audit mechanism
-- (public.appel_offre_commercial_ownership_events / appendAuditLog in
-- lib/appels-offres/repository.ts), which is hard-coupled to
-- appel_offres_id and does not fit this domain. It follows the same
-- *shape* of pattern instead (a small, dedicated, append-only event table
-- next to the entity it describes), matching how
-- appel_offre_commercial_ownership_events sits next to
-- public.appels_offres.commercial_owner_user_id.
--
-- Immutability (append-only, no UPDATE/DELETE) is enforced at the
-- application layer - only an INSERT is ever issued against this table, by
-- reviewArchiveFileClassification in app/administration/knowledge/actions.ts.
-- No update/delete function is exposed for it. This matches how every other
-- event/audit table in this codebase (app_auth_audit_events,
-- appel_offre_commercial_ownership_events) already enforces immutability by
-- convention rather than by database trigger.

CREATE TABLE IF NOT EXISTS knowledge_base.archive_file_classification_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Many events per file over time - deliberately NOT unique, unlike
  -- archive_file_classifications.archive_file_id.
  archive_file_id BIGINT NOT NULL
    REFERENCES knowledge_base.archive_files(id) ON DELETE CASCADE,

  -- Nullable: a file's first-ever review has no previous category/state
  -- beyond the implicit UNCLASSIFIED default (which IS recorded explicitly
  -- as previous_classification_state - see below - so only the category
  -- side can be genuinely NULL).
  previous_knowledge_category TEXT
    CHECK (previous_knowledge_category IN (
      'CDC', 'OFFER', 'PROJECT', 'METHODOLOGY', 'CV_CONSULTANT',
      'COMMERCIAL', 'FINANCIAL', 'ADMINISTRATIVE', 'OTHER', 'UNKNOWN'
    )),

  -- A human review always sets a concrete category - never NULL.
  new_knowledge_category TEXT NOT NULL
    CHECK (new_knowledge_category IN (
      'CDC', 'OFFER', 'PROJECT', 'METHODOLOGY', 'CV_CONSULTANT',
      'COMMERCIAL', 'FINANCIAL', 'ADMINISTRATIVE', 'OTHER', 'UNKNOWN'
    )),

  -- Always a concrete value (defaults to 'UNCLASSIFIED' when no prior row
  -- existed) - never NULL, unlike the category columns above.
  previous_classification_state TEXT NOT NULL
    CHECK (previous_classification_state IN (
      'UNCLASSIFIED', 'AUTO_FILTERED', 'AI_PROPOSED', 'NEEDS_REVIEW', 'VALIDATED'
    )),

  new_classification_state TEXT NOT NULL
    CHECK (new_classification_state IN (
      'UNCLASSIFIED', 'AUTO_FILTERED', 'AI_PROPOSED', 'NEEDS_REVIEW', 'VALIDATED'
    )),

  -- Provenance of THIS event. Currently only ever 'HUMAN' in practice
  -- (reviewArchiveFileClassification is the only writer), but the column
  -- allows the same table to record future RULE/LOCAL_AI transitions
  -- without a schema change. CLOUD_AI is deliberately not a valid value.
  classification_method TEXT NOT NULL
    CHECK (classification_method IN ('RULE', 'LOCAL_AI', 'HUMAN')),

  reason TEXT,

  -- Same reviewer FK pattern as archive_file_classifications.reviewed_by_user_id
  -- and public.appel_offre_commercial_ownership_events.changed_by_user_id.
  reviewed_by_user_id BIGINT REFERENCES public.app_users(id) ON DELETE SET NULL,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS archive_file_classification_events_file_idx
  ON knowledge_base.archive_file_classification_events(archive_file_id, created_at DESC);
CREATE INDEX IF NOT EXISTS archive_file_classification_events_reviewer_idx
  ON knowledge_base.archive_file_classification_events(reviewed_by_user_id, created_at DESC);

COMMIT;
