BEGIN;

-- Additive only. Does NOT modify knowledge_base.knowledge_documents or
-- knowledge_base.knowledge_document_versions in any way - the existing
-- CDC-specific historical-KB service and its columns/constraints/indexes
-- remain untouched. This table reuses those two tables for document/version
-- identity and provenance (filename, source_path, sha256, ingestion status)
-- via foreign key rather than duplicating that data, and adds only the
-- fields specific to a historical PROJECT/OFFER reference record: business
-- metadata, the approved embeddable summary, an explicit reuse/approval
-- status (which does not exist for CDC rows and must not be inferred), and
-- Qdrant indexing state.
CREATE TABLE IF NOT EXISTS knowledge_base.historical_project_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES knowledge_base.knowledge_documents(id) ON DELETE CASCADE,
  document_version_id BIGINT NOT NULL UNIQUE REFERENCES knowledge_base.knowledge_document_versions(id) ON DELETE CASCADE,

  -- Optional business identity, never fabricated when unknown.
  project_code TEXT,
  title TEXT,
  year TEXT,
  country TEXT,
  sector TEXT,
  subsector TEXT,
  project_type TEXT,
  client TEXT,
  funding_institution TEXT,
  nature_of_services TEXT,
  technical_scope TEXT,
  technical_components JSONB,
  key_deliverables JSONB,

  -- Provenance shown to a human reviewer/suggestion consumer. source_reference
  -- is a safe label (never a raw filesystem path); source_section is optional.
  source_reference TEXT NOT NULL,
  source_section TEXT,

  -- The ONLY free text ever embedded. Must be an approved, human-reviewable
  -- project/business summary - never raw document dumps, never consultant/CV
  -- content, never current-resource-availability claims.
  approved_summary_text TEXT NOT NULL,

  -- Explicit approval gate. Defaults to pending_review: nothing becomes
  -- retrievable merely by being inserted. Only 'approved_for_rag' rows may
  -- ever be embedded into the production collection.
  reuse_status TEXT NOT NULL DEFAULT 'pending_review'
    CHECK (reuse_status IN ('approved_for_rag', 'pending_review', 'rejected', 'archived')),

  -- Idempotency: stable hash of the deterministic embedding-text
  -- representation plus the metadata fields that feed it. Unchanged content
  -- on re-ingestion produces the same hash; changed approved content
  -- produces a new hash and triggers a deterministic re-embed/upsert.
  content_hash TEXT NOT NULL CHECK (content_hash ~ '^[a-f0-9]{64}$'),

  -- Indexing state, tracked separately from reuse_status: a record can be
  -- approved_for_rag but still 'pending' or 'failed' if embedding/Qdrant
  -- upsert has not yet succeeded. Never silently marked as if it were fully
  -- indexed on partial failure.
  index_status TEXT NOT NULL DEFAULT 'pending'
    CHECK (index_status IN ('pending', 'indexed', 'failed')),
  index_error_code TEXT,
  index_error_message TEXT,
  embedding_dimension INTEGER CHECK (embedding_dimension > 0),
  qdrant_collection TEXT,
  qdrant_point_id TEXT,
  indexed_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS historical_project_records_reuse_status_idx
  ON knowledge_base.historical_project_records(reuse_status);
CREATE INDEX IF NOT EXISTS historical_project_records_index_status_idx
  ON knowledge_base.historical_project_records(index_status);
CREATE INDEX IF NOT EXISTS historical_project_records_sector_idx
  ON knowledge_base.historical_project_records(sector);
CREATE INDEX IF NOT EXISTS historical_project_records_country_idx
  ON knowledge_base.historical_project_records(country);
CREATE INDEX IF NOT EXISTS historical_project_records_project_type_idx
  ON knowledge_base.historical_project_records(project_type);
CREATE INDEX IF NOT EXISTS historical_project_records_content_hash_idx
  ON knowledge_base.historical_project_records(content_hash);
CREATE UNIQUE INDEX IF NOT EXISTS historical_project_records_qdrant_point_id_key
  ON knowledge_base.historical_project_records(qdrant_point_id)
  WHERE qdrant_point_id IS NOT NULL;

COMMIT;
