-- Transaction boundaries are managed by the migration runner. Apply this
-- migration inside an explicit transaction.

-- Provenance for a completed human-review workbook import into
-- knowledge_base.historical_technical_source_candidates (the
-- "CDC utilisable ?" review round). Additive only.
--
-- APPLIED AND LIVE-VERIFIED on GONOGO on 2026-09-18. This file remains the
-- source-of-truth migration; CREATE TABLE IF NOT EXISTS / CREATE INDEX IF
-- NOT EXISTS make it safe to rerun.
--
-- WHY A NEW TABLE INSTEAD OF REUSING AN EXISTING ONE: before proposing
-- this, the codebase was inspected for a reusable mechanism.
--   - knowledge_base.knowledge_ingestion_runs (scripts/sql/20260818_
--     knowledge_base.sql) looked promising by name but is tightly coupled
--     to the RAG/Qdrant document-ingestion pipeline - document_id/
--     document_version_id FK into knowledge_documents/knowledge_document_
--     versions, and qdrant_collection is NOT NULL with no default. Forcing
--     an unrelated human-review import through it would mean either
--     fabricating a fake document/version row or leaving a NOT NULL column
--     unfillable - a semantic misuse, not a reuse.
--   - knowledge_base.archive_file_classification_events (scripts/sql/
--     20260829_archive_cartography_classification_events.sql) is the
--     right SHAPE (append-only human-review audit event) but is scoped to
--     a different table (archive_file_classifications, keyed by
--     archive_file_id) and a different classification model entirely.
--   - knowledge_base.historical_technical_source_ai_reviews already
--     establishes this exact pipeline's convention for hash-based
--     idempotency (content_sha256, idempotency_key) - but at the
--     per-candidate-row grain, for a machine review pass, not a
--     per-import-run grain.
--   - knowledge_base.archive_scan_runs is the closest true precedent: one
--     row per RUN of a pipeline stage, with status/started_at/completed_at
--     and aggregate integer counts. This table mirrors that shape.
--
-- GRANULARITY: one row per import RUN, not one row per candidate. Per the
-- explicit instruction this migration was written under: do not add
-- source_workbook_sha256 independently to every candidate row unless
-- repository conventions strongly require it - they don't; every other
-- "run" table in this schema records provenance once per run, not
-- duplicated onto every row the run touched. See the companion migration
-- (add_historical_technical_source_candidates_import_batch_link.sql) for
-- how an individual candidate row is linked back to the batch that
-- touched it, without duplicating the batch's own provenance fields onto
-- every row.
--
-- EXTERNAL REVIEWER MODEL (revised): the app_users table represents
-- internal CONCEPT staff with login accounts. Youssef, the human who
-- completed this review round, is an EXTERNAL reviewer with no app_users
-- account - and per explicit product decision, one must never be
-- fabricated solely to satisfy a NOT NULL foreign key. This table
-- therefore supports two mutually exclusive reviewer representations:
--   - INTERNAL_USER: reviewer_user_id is a real app_users FK, exactly like
--     historical_technical_source_candidates.reviewed_by already works.
--   - EXTERNAL_HUMAN: reviewer_user_id stays NULL (truthfully - no
--     internal account performed the review) and external_reviewer_label
--     records who did, as a short plain-text label (e.g. "Youssef") - not
--     an email, not a full identity record, just enough for provenance.
-- The CHECK constraint below makes the two modes mutually exclusive and
-- each internally complete, so a row can never claim both an internal
-- reviewer identity and an external label, and can never claim
-- EXTERNAL_HUMAN without actually naming who reviewed it.
--
-- CONFIDENTIALITY: no workbook path, filename, document title, comment, or
-- any cell content is ever stored here - only a hash, a short reviewer
-- label, counts, and status/timestamps.
--
-- Does NOT alter knowledge_base.historical_technical_source_candidates,
-- historical_technical_source_ai_reviews, archive_files, or any other
-- existing table in any way. Creates one new, empty table plus its
-- supporting indexes only. (The candidate-to-batch link column is a
-- SEPARATE, companion migration - see above.)

CREATE SCHEMA IF NOT EXISTS knowledge_base;

CREATE TABLE IF NOT EXISTS knowledge_base.historical_technical_source_import_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Idempotency key: re-running the importer against the exact same
  -- workbook content must be detectable and safe (see the importer's
  -- "idempotent for an already-applied identical workbook" requirement).
  -- Same CHECK shape as knowledge_document_versions.sha256.
  source_workbook_sha256 TEXT NOT NULL UNIQUE
    CHECK (source_workbook_sha256 ~ '^[a-f0-9]{64}$'),

  -- Who reviewed the workbook - see "EXTERNAL REVIEWER MODEL" above.
  reviewer_type TEXT NOT NULL
    CHECK (reviewer_type IN ('INTERNAL_USER', 'EXTERNAL_HUMAN')),

  reviewer_user_id BIGINT REFERENCES public.app_users(id) ON DELETE RESTRICT,

  -- Minimum provenance label for an external reviewer - a short name, not
  -- an email/identity record. Length-capped defensively so this column can
  -- never become a place to smuggle in a comment or document excerpt.
  external_reviewer_label TEXT
    CHECK (external_reviewer_label IS NULL OR length(external_reviewer_label) <= 100),

  CHECK (
    (reviewer_type = 'INTERNAL_USER' AND reviewer_user_id IS NOT NULL AND external_reviewer_label IS NULL)
    OR
    (reviewer_type = 'EXTERNAL_HUMAN' AND reviewer_user_id IS NULL AND external_reviewer_label IS NOT NULL)
  ),

  -- The internal operator who RAN the importer on the external reviewer's
  -- behalf - independent of reviewer_type/reviewer_user_id (who made the
  -- review DECISION). Always optional: only set when a real internal
  -- operator identity is actually available and authorized, never
  -- fabricated to fill this column.
  imported_by_user_id BIGINT REFERENCES public.app_users(id) ON DELETE SET NULL,

  -- Same run-lifecycle shape as archive_scan_runs.status, spelled out in
  -- the same style as this schema's other enum-like status columns.
  status TEXT NOT NULL DEFAULT 'IN_PROGRESS'
    CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED', 'ROLLED_BACK')),

  importer_version TEXT NOT NULL,

  total_count INTEGER NOT NULL DEFAULT 0 CHECK (total_count >= 0),
  usable_count INTEGER NOT NULL DEFAULT 0 CHECK (usable_count >= 0),
  excluded_count INTEGER NOT NULL DEFAULT 0 CHECK (excluded_count >= 0),
  skipped_uncertain_count INTEGER NOT NULL DEFAULT 0 CHECK (skipped_uncertain_count >= 0),
  updated_count INTEGER NOT NULL DEFAULT 0 CHECK (updated_count >= 0),

  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  error_message TEXT,

  CHECK (usable_count + excluded_count + skipped_uncertain_count <= total_count),
  CHECK (updated_count <= usable_count + excluded_count)
);

CREATE INDEX IF NOT EXISTS historical_technical_source_import_batches_reviewer_user_idx
  ON knowledge_base.historical_technical_source_import_batches(reviewer_user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS historical_technical_source_import_batches_status_idx
  ON knowledge_base.historical_technical_source_import_batches(status, started_at DESC);
CREATE INDEX IF NOT EXISTS historical_technical_source_import_batches_source_hash_idx
  ON knowledge_base.historical_technical_source_import_batches(source_workbook_sha256);

-- Reversal (documented, not applied automatically - a human runs this only
-- if the migration above needs to be undone before any dependent data
-- exists, and only AFTER the companion candidate-link migration has been
-- reversed first, since that migration's FK references this table):
--   BEGIN;
--   DROP TABLE IF EXISTS knowledge_base.historical_technical_source_import_batches;
--   COMMIT;
